#!/usr/bin/python3

# intrest
"""
Simple Command Line intrest Calqulator
"""
# >>>>>>>>>>>  add useage dialog


def monetize(num):
    num = ("$" + str(format(float(num), ',.2f')))
    return num


print("\n\n\n\t\t\033[1;33m$$$\033[1;32m INTREST \033[1;33m$$$\033[0m\n\n")


invest_ammount = int(input("\033[1;32mAmmount \033[1;33m>>>\033[0m "))
intrest = int(input("\n\033[1;32mIntrest \033[1;33m>>>\033[0m "))
term_lenght = int(input("\n\033[1;32mTerm \033[1;33m>>>\033[0m "))


n = 0
while n < int(term_lenght):
    n += 1
    turd = invest_ammount * (intrest / 100 + 1)
    gain = turd - invest_ammount
    invest_ammount = turd
    print("Term " + str(n) + ": " + monetize(turd) +
          " ----- Gain: " + monetize(gain))
