#!/usr/bin/python3

# stockwatch

####
#example

#Need to pull from web
Current_sharePrice = 7000
boughtPrice = 5000

##
tax = 0.3
dbTrade = 18
shareGain = format(((Current_sharePrice / boughtPrice -1) *100), '.1f')
grossProfit = Current_sharePrice - boughtPrice 
netProfit = grossProfit - ( grossProfit * tax ) - dbTrade
pure_net_percent = format(((netProfit/boughtPrice) * 100), '.1f')
print ("Gross: %r ----- Net: %r ----- Gain: %r ------- PNP : %r" % (grossProfit,netProfit,shareGain,pure_net_percent))


"""
color code
green, blue, red, yellow, 
if PNP:
PNP < 0 --red
0<PNP<3.0 --yellow
3.0<=PNP<=8.2 --green 1
8.3<=PNP<=16.9 --green 2
PNP > 17 -- Blue
"""
